// <auto-generated />
using System;
using CompareRemedios.Dominio.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompareRemedios.Dominio.Migrations
{
    [DbContext(typeof(CompareRemediosContext))]
    [Migration("20181011222254_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompareRemedios.Dominio.Entidades.Farmacia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnName("NomeFantasia")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("Farmacia");
                });

            modelBuilder.Entity("CompareRemedios.Dominio.Entidades.Preco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FarmaciaId");

                    b.Property<int?>("ProdutoId");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("FarmaciaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Preco");
                });

            modelBuilder.Entity("CompareRemedios.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<int?>("FarmaciaId");

                    b.HasKey("Id");

                    b.HasIndex("FarmaciaId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("CompareRemedios.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeCompleto");

                    b.Property<string>("Senha");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CompareRemedios.Dominio.Entidades.Preco", b =>
                {
                    b.HasOne("CompareRemedios.Dominio.Entidades.Farmacia", "Farmacia")
                        .WithMany()
                        .HasForeignKey("FarmaciaId");

                    b.HasOne("CompareRemedios.Dominio.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("CompareRemedios.Dominio.Entidades.Produto", b =>
                {
                    b.HasOne("CompareRemedios.Dominio.Entidades.Farmacia", "Farmacia")
                        .WithMany()
                        .HasForeignKey("FarmaciaId");
                });
#pragma warning restore 612, 618
        }
    }
}
